all:
	g++ generate_random_inputs.cpp -o genip
	./genip
	g++ main_AVL_insert_search.cpp -o AVL
	./AVL
	g++ main_AVL_insert_search_hash.cpp -o AVLhash
	./AVLhash
	g++ main_RB_insert_search.cpp -o RB
	./RB
	g++ main_RB_insert_search_hash.cpp -o RBhash
	./RBhash
	g++ main_Btree_insert_search.cpp -o BTREE
	./BTREE
	g++ main_Btree_insert_search_hash.cpp -o BTREEhash
	./BTREEhash
